name: Publish & Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'views/**'
      - 'locales/**'
  workflow_dispatch:

env:
  TAG: master
  IMAGE_NAME: ghcr.io/invoice-collector/invoice-collector
  IMAGE_NAME_PREMIUM: ghcr.io/invoice-collector/invoice-collector-premium
  DEPLOYMENT_NAME_DEMO: invoice-collector-demo
  DEPLOYMENT_NAME_PROD: invoice-collector-prod

permissions:
  contents: write
  packages: write

jobs:
  publish-image-to-github:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        target: prod
        build-args: |
          BUILD_ENV=production
        platforms: linux/amd64
        push: true
        provenance: false
        tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}

  publish-premium-image-to-github:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: true
        token: ${{ secrets.PAT_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        target: prod
        build-args: |
          BUILD_ENV=production
        platforms: linux/amd64
        push: true
        provenance: false
        tags: |
            ${{ env.IMAGE_NAME_PREMIUM }}:${{ env.TAG }}

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: publish-premium-image-to-github

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
        submodules: true
        token: ${{ secrets.PAT_TOKEN }}

    - name: Reload Production Deployment
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        args: rollout restart deployment/${{ env.DEPLOYMENT_NAME_PROD }}
